import climate_science_regional_climate_modeling_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace climate_science_regional_climate_modeling_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end climate_science_regional_climate_modeling_lemma_canonical_lane_mathlib
end HautevilleHouse
